# Generated by Django 5.0.6 on 2024-05-20 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_book_description_book_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='biography',
            new_name='bio',
        ),
    ]
